import React from 'react';
import { Link } from 'react-router-dom';

const PrivacyPolicy = () => {
  return (
    <div className="max-w-4xl mx-auto px-4 py-16">
      <h1 className="text-3xl font-bold mb-8 text-center">Privacy Policy for Knight Kavalier</h1>
      
      <div className="prose max-w-none">
        <p className="text-right mb-8 text-gray-600">Last updated: June 02, 2025</p>
        
        <p className="mb-6">
          This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
        </p>
        
        <p className="mb-12">
          We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the Privacy Policy Generator.
        </p>

        <h2 className="text-2xl font-semibold mt-8 mb-4">Interpretation and Definitions</h2>
        <h3 className="text-xl font-medium mt-6 mb-2">Interpretation</h3>
        <p className="mb-4">
          The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
        </p>

        <h3 className="text-xl font-medium mt-6 mb-2">Definitions</h3>
        <p className="mb-4">For the purposes of this Privacy Policy:</p>
        
        <ul className="list-disc pl-6 mb-6 space-y-2">
          <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
          <li><strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
          <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Knight Kavalier, 555, Rex textiles, I-Block, Satabdipuram, Gwalior, M.P., India, 474020.</li>
          <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
          <li><strong>Country</strong> refers to: Madhya Pradesh, India</li>
          <li><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
          <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
          <li><strong>Service</strong> refers to the Website.</li>
          <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company.</li>
          <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</li>
          <li><strong>Website</strong> refers to Knight Kavalier, accessible from <Link to="/" className="text-blue-600 hover:underline">http://www.knightkavalier.com</Link></li>
          <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
        </ul>

        <h2 className="text-2xl font-semibold mt-12 mb-4">Collecting and Using Your Personal Data</h2>
        <h3 className="text-xl font-medium mt-6 mb-2">Types of Data Collected</h3>
        <h4 className="text-lg font-medium mt-4 mb-2">Personal Data</h4>
        <p className="mb-4">
          While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
        </p>
        <ul className="list-disc pl-6 mb-6 space-y-1">
          <li>Email address</li>
          <li>First name and last name</li>
          <li>Phone number</li>
          <li>Address, State, Province, ZIP/Postal code, City</li>
          <li>Usage Data</li>
        </ul>

        <h4 className="text-lg font-medium mt-6 mb-2">Usage Data</h4>
        <p className="mb-4">
          Usage Data is collected automatically when using the Service. Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
        </p>
        <p className="mb-6">
          When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.
        </p>

        <h3 className="text-xl font-medium mt-8 mb-2">Tracking Technologies and Cookies</h3>
        <p className="mb-4">
          We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service.
        </p>
        <p className="mb-6">
          For more information about the cookies we use and your choices regarding cookies, please visit our <Link to="/cookies-policy" className="text-blue-600 hover:underline">Cookies Policy</Link>.
        </p>

        <h2 className="text-2xl font-semibold mt-12 mb-4">Use of Your Personal Data</h2>
        <p className="mb-4">The Company may use Personal Data for the following purposes:</p>
        <ul className="list-disc pl-6 mb-6 space-y-2">
          <li>To provide and maintain our Service</li>
          <li>To manage Your Account</li>
          <li>For the performance of a contract</li>
          <li>To contact You</li>
          <li>To provide You with news, special offers and general information</li>
          <li>To manage Your requests</li>
          <li>For business transfers</li>
          <li>For other purposes: We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.</li>
        </ul>

        <p className="mb-6">
          We may share Your personal information in various situations, including with Service Providers, for business transfers, with Affiliates, with business partners, with other users when You interact in public areas, and with Your consent.
        </p>

        <h2 className="text-2xl font-semibold mt-12 mb-4">Retention of Your Personal Data</h2>
        <p className="mb-6">
          The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our legal agreements and policies.
        </p>

        <h2 className="text-2xl font-semibold mt-12 mb-4">Security of Your Personal Data</h2>
        <p className="mb-6">
          The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.
        </p>

        <h2 className="text-2xl font-semibold mt-12 mb-4">Children's Privacy</h2>
        <p className="mb-6">
          Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us.
        </p>

        <h2 className="text-2xl font-semibold mt-12 mb-4">Links to Other Websites</h2>
        <p className="mb-6">
          Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.
        </p>

        <h2 className="text-2xl font-semibold mt-12 mb-4">Changes to this Privacy Policy</h2>
        <p className="mb-6">
          We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page and updating the "Last updated" date at the top of this Privacy Policy.
        </p>

        <h2 className="text-2xl font-semibold mt-12 mb-4">Contact Us</h2>
        <p className="mb-2">If you have any questions about this Privacy Policy, You can contact us:</p>
        <ul className="list-disc pl-6 mb-12 space-y-1">
          <li>By email: <a href="mailto:textiles.rex@gmail.com" className="text-blue-600 hover:underline">textiles.rex@gmail.com</a></li>
          <li>By visiting this page on our website: <Link to="/contact" className="text-blue-600 hover:underline">Contact Us</Link></li>
        </ul>
      </div>
    </div>
  );
};

export default PrivacyPolicy;
